#+title: janus-key

janus-key provides keys with a secondary function, so that they send
one input when pressed and released, but another input when held down
and used in combination with other keys.

janus-key sits at a [[https://www.freedesktop.org/software/libevdev/doc/latest/][relatively low level]], so it works regardless of
whether you are using X, Wayland or neither.

janus-key does not require systemd.

Configuration is simple.

* Possible usages
- Turning normal keys (e.g. CAPSLOCK or ENTER) into modifiers
  (e.g. CTRL or ALT) when held down. Emacs users, for example, can do
  so to keep their pinkie healthy without indulging in the [[https://en.wikipedia.org/wiki/Editor_war#Humor][keybindings
  of the beast]].
- Turning modifiers into normal keys when pressed and
  released. Vim/evil users, for example, can do so to exit insert mode
  by pressing an easily reachable modifier.

* Dependencies
Install *libevdev* on your system if you have not already.

* Configuration
Edit the janus_map in config.h

For example, the following simply turns ESC into CAPSLOCK:
#+begin_src C
  {  KEY_ESC,           KEY_CAPSLOCK  }
#+end_src

The following makes ENTER behave as RIGHTALT when held down, leaving
untouched ENTER's behaviour when pressed and released:
#+begin_src C
  {  KEY_ENTER,         0,               KEY_RIGHTALT    }
#+end_src

The following changes both CAPSLOCK's primary function and secondary
function, so that it behaves as ESC when pressed and released, but as
LEFTALT when held down:
#+begin_src C
  {  KEY_CAPSLOCK,      KEY_ESC,         KEY_LEFTALT     }
#+end_src

You can find the names of the keys of a certain device by using
*evtest*.

A key sends its primary function if pressed and relased /within a
certain time/.  To set this time change the value of ~max_delay~ (see
the config.h file for info).

* Compile and run
Compile with
#+begin_src
gcc `pkg-config --cflags libevdev` janus-key.c `pkg-config --libs libevdev` -o janus-key
#+end_src

Run
#+begin_src
sudo ./janus-key /dev/input/event<NUMBER>
#+end_src

* 
janus-key

Copyright (C) 2021  Giulio Pietroiusti

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
